---
- name: Onboard BIG-IP
  hosts: bigip1a
  gather_facts: false
  connection: local
  vars:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ admin_user }}"
      password: "{{ admin_default_password }}"
      validate_certs: false

  tasks:
  - name: Set Timezone and NTP Server
    bigip_device_ntp:
      timezone: America/Los_Angeles
      ntp_servers:
      - pool.ntp.org
      provider: "{{ provider }}"
