---
- name: Play 1 - gather and show facts for the hosts in the inventory file
  hosts: all
  gather_facts: false
  vars:
    fact_dir: ~/.ansible/facts/
  tasks:
  - name: Task 1 - create new facts directory
    file:
      path: "{{ fact_dir }}"
      state: directory
  - name: Task 2 - copy custom fact script to remot host
    copy:
      src: ~/facts/get_version.fact
      dest: "{{ fact_dir }}"
      mode: 0755
  - name: Task 3 - load facts
    setup:
      fact_path: "{{ fact_dir }}"
  - name: Task 4 - show version
    debug:
      var: ansible_local.get_version.version
