---
- name: Play 1 - list the hosts in the inventory file
  hosts: all
  gather_facts: false
  tasks:
  - name: Task 1 - print hostname (repeat for each host)
    debug:
      var: inventory_hostname
